### ISSUE TITLE
App crashes in startup 

### ISSUE THREAD

**Issue by nascado** [hansemannn/titanium-image-crop#1]
When trying to run the app, which works perfectly with XCode 11.5 and Ti SDK 8.3.1 or 9.0.2, with this module the app crashes immediatly on startup.

Operating System
  Name                        = Mac OS X
  Version                     = 10.15.5
  Architecture                = 64bit
  # CPUs                      = 6
  Memory                      = 51539607552
Node.js
  Node.js Version             = 10.19.0
  npm Version                 = 6.14.2
Titanium CLI
  CLI Version                 = 5.2.2
Titanium SDK
  SDK Version                 = 9.0.0.GA
  SDK Path                    = /Users/marco/Library/Application Support/Titanium/mobilesdk/osx/9.0.0.GA
  Target Platform             = iphone

I tried to recompile the module but this didn´t work due to the old Swift 3 version.
Then i tried to update the sources to Swift 4 with Xcode 10.1 but this crashes as well with missing TitaniumKit.

Sorry to bother, but I need yourt help.
Thanks in advance

**Comment by linearshift** [comment]
I had pretty much the same problem, but running on 8.3.1. App always gets stuck on the loading screen, and then the app will not launch again until the module is completely removed.

New to modules / Swift - so any pointers in the right direction would be greatly appreciated, this looks like it would be a really handy library.

**Comment by hansemannn** [comment]
Yep, it needs a Swift version update. Doing right now
