### ISSUE TITLE
ImageCrop dialog opens only once

### ISSUE THREAD

**Issue by designbymind** [hansemannn/titanium-image-crop#2]
First off, this is an awesome module, **Thank You** for open sourcing =]

After successfully showing the ImageCrop dialog, then clicking the "Cancel" button, then attempting to show the ImageCrop dialog again, nothing happens (no dialog shows, no error thrown).

**Any idea why the above is happening?** — Possibly something to do with the ImageCrop not being able to take the position as `topPresentedController`?

**Side Note:** when attempting to open ImageCrop _directly_ after selecting an image from Photo Gallery (in the `success` callback of `Ti.Media.openPhotoGallery`), ImageCrop will not display without a `setTimeout`. — Possibly a race condition for the `topPresentedController`?

**TiSDK:** 10.1.0.v20210806050748
**iOS:** 14.5

**Comment by hansemannn** [comment]
Thanks! Fixed in https://github.com/hansemannn/titanium-image-crop/commit/6f2fe4e68b5666e74b213284e1929698c6265068
